language: node_js
node_js:
  - 8

cache:
  directories:
    - ./packages/cra-template-rmw/template/node_modules
    - ./packages/cra-template-rmw/template/functions/node_modules

before_install:
  - chmod +x ./packages/cra-template-rmw/template/continuous_deployment/before_install.sh
  - ./packages/cra-template-rmw/template/continuous_deployment/before_install.sh

before_script:
  - cd ./packages/cra-template-rmw/template/
  - npm test
  - chmod +x ./packages/cra-template-rmw/template/continuous_deployment/build.sh
  - travis_wait 40 ./packages/cra-template-rmw/template/continuous_deployment/build.sh

script:
  - chmod +x ./packages/cra-template-rmw/template/continuous_deployment/deploy.sh
  - travis_wait 40 ./packages/cra-template-rmw/template/continuous_deployment/deploy.sh
