name: base-shell
on:
  push:
    branches:
      - master
    paths:
      - "packages/base-shell/src/**"
      - "packages/base-shell/cra-template-base/template/**"
  workflow_dispatch:
jobs:
  base-shell:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: https://registry.npmjs.org/
          working-directory: ./packages/base-shell
      - name: Install dependencies
        run: npm i
        working-directory: ./packages/base-shell
      - name: Publish
        run: npm publish
        working-directory: ./packages/base-shell
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  base-shell-template:
    if: ${{ always() }}
    needs: [base-shell]
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: https://registry.npmjs.org/
          working-directory: ./packages/base-shell/cra-template-base
      - name: Install dependencies
        run: npm i
        working-directory: ./packages/base-shell/cra-template-base
      - name: Publish
        run: npm publish
        working-directory: ./packages/base-shell/cra-template-base
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
