name: base-shell
on:
  push:
    branches:
      - master
    paths:
      - "packages/base-shell/src/**"
      - "packages/base-shell/cra-template-base/template/**"
  workflow_dispatch:
jobs:
  base-shell:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org/
          working-directory: ./packages/base-shell
      - name: Install release-it
        run: npm i -g release-it
      - name: Install dependencies
        run: npm i
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: git pull
        run: git pull
      - name: Publish
        run: npm run release
        working-directory: ./packages/base-shell
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  base-shell-template:
    if: ${{ always() }}
    needs: [base-shell]
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org/
          working-directory: ./packages/base-shell/cra-template-base
      - name: Install release-it
        run: npm i -g release-it
      - name: Install dependencies
        run: npm i
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: git pull
        run: git pull
      - name: Publish
        run: npm run release 
        working-directory: ./packages/base-shell/cra-template-base
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
