name: base-shell deploymend

on:
  push:
    branches: [$default-branch]
  paths:
    - 'packages/base-shell/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm test
