name: rmw-shell demo deploy
on: [push, workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v2
        uses: actions/setup-node@v2
      - run: npm i
