name: material-ui-shell
on:
  push:
    branches:
      - master
    paths:
      - "packages/material-ui-shell/src/**"
      - "packages/material-ui-shell/cra-template-material-ui/template/**"
  workflow_dispatch:
jobs:
  material-ui-shell:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: https://registry.npmjs.org/l
      - name: Install dependencies
        run: npm i
        working-directory: ./packages/material-ui-shell
      - name: Publish
        run: npm publish
        working-directory: ./packages/material-ui-shell
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  material-ui-shell-template:
    if: ${{ always() }}
    needs: [material-ui-shell]
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm i
        working-directory: ./packages/material-ui-shell/cra-template-material-ui
      - name: Publish
        run: npm run release
        working-directory: ./packages/material-ui-shell/cra-template-material-ui
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
