name: rmw-shell-template
on:
  push:
    paths:
      - "packages/rmw-shell/cra-template-rmw/**.json"
  workflow_dispatch:
    
jobs:
  rmw-shell-npm-publish:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm i
        working-directory: ./packages/rmw-shell/craco-template-rmw
      - name: Publish
        run: npm publish
        working-directory: ./packages/rmw-shell/craco-template-rmw
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
