name: rmw-shell-demo
on:
  push:
    paths:
      - "packages/rmw-shell/cra-template-rmw/template/**"
      - "packages/rmw-shell/src/**"
  workflow_dispatch:
    
jobs:
  rmw-shell-demo:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: install-rmw-shell
        run: npx create-react-app demo-app --template rmw --use-npm
      - name: install firebase functins dependencies  
        run: npm i
        working-directory: ./demo-app/firebase/functions
      - name: run build     
        run: |
          npm run build
        env:
          CI: false
        working-directory: ./demo-app
      - name: Install firebase tools
        run: npm i -g firebase-tools
      - name: Deploy
        run: |
          firebase use prod
          firebase deploy --only hosting --token $FIREBASE_TOKEN
        working-directory: ./demo-app
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
