name: rmw-shell-demo
on: [push, workflow_dispatch]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npx create-react-app demo-app --template rmw --use-npm
      - run: cd demo-app
