name: rmw-shell-demo
on: [push, workflow_dispatch]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: install-rmw-shell
        run: npx create-react-app demo-app --template rmw --use-npm
      - name: install firebase functins dependencies  
        run: npm i
        working-directory: ./demo-app/firebase/functions
      - name: run build     
        run: |
          process.env.CI = false
          npm run build
          process.env.CI = true
        env:
          CI: false
        working-directory: ./demo-app
